apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app1.fullname" . }}-html
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>App1 Page</title>
    </head>
    <body>
        <h1>Welcome to App1!</h1>
        <p>This is a sample page served by Nginx in App1.</p>
    </body>
    </html>
